//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.GstSystems = new HashSet<GstSystem>();
            this.Industries = new HashSet<Industry>();
            this.CurrencySchedulars = new HashSet<CurrencySchedular>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Permission { get; set; }
        public string CompanyID { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CurrencySchedularId { get; set; }
    
        public virtual ICollection<GstSystem> GstSystems { get; set; }
        public virtual ICollection<Industry> Industries { get; set; }
        public virtual ICollection<CurrencySchedular> CurrencySchedulars { get; set; }
    }
}
