//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public string logoname { get; set; }
        public string dateformat { get; set; }
        public string timeformat { get; set; }
        public string dbaddress { get; set; }
        public string dbname { get; set; }
        public string dbuserid { get; set; }
        public string dbpwd { get; set; }
        public string directorypath { get; set; }
    }
}
