//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencySchedular
    {
        public int Id { get; set; }
        public string FeedUrl { get; set; }
        public string FrequencyUnit { get; set; }
        public string Time { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime NextRunDate { get; set; }
        public System.TimeSpan NextRunTime { get; set; }
        public System.DateTime LastRun { get; set; }
        public string Status { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
