//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public int Id { get; set; }
        public string SystemId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Supply { get; set; }
        public string Purchase { get; set; }
        public string Ledger { get; set; }
        public string Footer { get; set; }
        public string Company { get; set; }
        public string CycleID { get; set; }
        public string Status { get; set; }
        public string UserId { get; set; }
    }
}
