//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSTMARTEntities : DbContext
    {
        public GSTMARTEntities()
            : base("name=GSTMARTEntities")
        {
        }
        public GSTMARTEntities(string con)
            : base(con)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminPath> AdminPaths { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Cycle> Cycles { get; set; }
        public DbSet<GstSystem> GstSystems { get; set; }
        public DbSet<IpAddress> IpAddresses { get; set; }
        public DbSet<LDAP> LDAPs { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<Schedular> Schedulars { get; set; }
        public DbSet<Industry> Industries { get; set; }
        public DbSet<TaxCode> TaxCodes { get; set; }
        public DbSet<CustomCode> CustomCodes { get; set; }
        public DbSet<TransactionType> TransactionTypes { get; set; }
        public DbSet<CurrencyExchange> CurrencyExchanges { get; set; }
        public DbSet<OriginalCodeTax> OriginalCodeTaxes { get; set; }
        public DbSet<CurrencyType> CurrencyTypes { get; set; }
        public DbSet<CurrencyGroup> CurrencyGroups { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<CurrencySchedular> CurrencySchedulars { get; set; }
    }
}
