//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDAP
    {
        public int Id { get; set; }
        public string DomianName { get; set; }
        public string PortNumber { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string CompanyId { get; set; }
        public string CNBN { get; set; }
    }
}
