//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public string CreateCycle { get; set; }
        public string AccessSetting { get; set; }
        public string DownloadData { get; set; }
        public string PrintReport { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
