//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedular
    {
        public int Id { get; set; }
        public string Module { get; set; }
        public string Path { get; set; }
        public string Frequency { get; set; }
        public string Unit { get; set; }
        public string STime { get; set; }
        public string Status { get; set; }
        public string LastRun { get; set; }
        public string NextRun { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CompanyID { get; set; }
    }
}
