//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STAGEDBGSTMASRTEntities : DbContext
    {
        public STAGEDBGSTMASRTEntities()
            : base("name=STAGEDBGSTMASRTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ErrorLogger> ErrorLoggers { get; set; }
        public DbSet<tbl_DupLedger> tbl_DupLedger { get; set; }
        public DbSet<tbl_GSTCompany> tbl_GSTCompany { get; set; }
        public DbSet<tbl_GSTDupCompany> tbl_GSTDupCompany { get; set; }
        public DbSet<tbl_GSTDupPurchase> tbl_GSTDupPurchase { get; set; }
        public DbSet<tbl_GSTErrorCompany> tbl_GSTErrorCompany { get; set; }
        public DbSet<tbl_GSTErrorFooter> tbl_GSTErrorFooter { get; set; }
        public DbSet<tbl_GSTFooter> tbl_GSTFooter { get; set; }
        public DbSet<tbl_GSTMissingCompany> tbl_GSTMissingCompany { get; set; }
        public DbSet<tbl_GSTMissingFooter> tbl_GSTMissingFooter { get; set; }
        public DbSet<tbl_GSTMissingPurchase> tbl_GSTMissingPurchase { get; set; }
        public DbSet<tbl_GSTPurchase> tbl_GSTPurchase { get; set; }
        public DbSet<tbl_GSTPurchaseError> tbl_GSTPurchaseError { get; set; }
        public DbSet<tbl_GSTSupply> tbl_GSTSupply { get; set; }
        public DbSet<tbl_GSTSupplyError> tbl_GSTSupplyError { get; set; }
        public DbSet<tbl_Ledger> tbl_Ledger { get; set; }
        public DbSet<tbl_MissingLedger> tbl_MissingLedger { get; set; }
        public DbSet<tbl_GSTDupSupply> tbl_GSTDupSupply { get; set; }
        public DbSet<tbl_GSTMissingSuplly> tbl_GSTMissingSuplly { get; set; }
    }
}
