//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ledger
    {
        public long Ledger_ID { get; set; }
        public string Company_Code { get; set; }
        public string Record_Identifier { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Account_ID { get; set; }
        public string Account_Name { get; set; }
        public string Transaction_Description { get; set; }
        public string Transaction_ID { get; set; }
        public string Source_Document_ID { get; set; }
        public string Source_Type { get; set; }
        public string Transaction_Type { get; set; }
        public string Tax_Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<long> CycleID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CompanyID { get; set; }
    }
}
