//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Purchase
    {
        public int id { get; set; }
        public string CompanyCode { get; set; }
        public string TransactionType { get; set; }
        public string SupplierNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplierBRN { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string ImportDeclarationNo { get; set; }
        public string NumberInvoiceLine { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> ValuePurchaseExcluding { get; set; }
        public Nullable<decimal> ValueGSTMYR { get; set; }
        public string TaxCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ValuePurchaseExcludingGST { get; set; }
        public Nullable<decimal> ValueGSTForex { get; set; }
        public string CycleID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CompanyID { get; set; }
    }
}
