//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GSTMissingPurchase
    {
        public long Purchase_ID { get; set; }
        public string Company_Code { get; set; }
        public string Record_Identifier { get; set; }
        public string Supplier_BRN { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Invoice_No { get; set; }
        public string Import_Declaration_No { get; set; }
        public string Line_No { get; set; }
        public string Product_Description { get; set; }
        public Nullable<decimal> Purchase_Value_MYR { get; set; }
        public Nullable<decimal> Purchase_Value_GST_Amount { get; set; }
        public string Tax_Code { get; set; }
        public string Foreign_Currency_Code { get; set; }
        public Nullable<decimal> Purchase_Foreign_Currency_Amount { get; set; }
        public Nullable<decimal> Purchase_Currency_Purchase_Amount_GST { get; set; }
        public Nullable<int> YR { get; set; }
        public Nullable<int> MTH { get; set; }
        public Nullable<long> Cycle_ID { get; set; }
        public Nullable<decimal> Value_Exempt_Supplies { get; set; }
        public string Transaction_Type { get; set; }
        public string Supplier_Number { get; set; }
        public string Product_Code { get; set; }
        public string CompanyID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
